# Thanks For Using My Plugin.
# Permissions:
# - ultrahardcore.unban
# - ultrahardcore.alert
# - ultrahardcore.reload
# - ultrahardcore.clearchat
# - ultrahardcore.freeze

# Punishment Options
Punishment:
  Reason: "&cYou Are Dead"
  Ban: true

# Join Announcement Options - Use {PlayerName} For Player Name
JoinOptions:
  Enabled: true
  FirstJoinAnnouncementMessage: "&a&l+&7 {PlayerName} &eJust Logged In For The First Time"
  JoinAnnouncementMessage: "&a&l+ &eEveryone Welcome&7 {PlayerName}"
  QuitAnnouncementMessage: "&c&l- &eEveryone Say GoodBye To&7 {PlayerName}"
#  JoinDiscordWebhook:
#    Enabled: false  # This option is unavailable currently.
#    Webhook-URL: "paste your discord webhook url here."

# /SocialMedia URLs
SocialMedia:
  Website-URL: "https://www.yourwebsite.ultrahardcore"
  Instagram-URL: "https://www.instagram.com"
  Discord-URL: "https://www.discord.gg"

# ActionBar XYZ Options
ActionBarOptions:
  Enabled: true

# Sleep Options
SleepOptions:
  OnePlayerSleep:
    Enabled: true
    # WakeUp Message Will Not Be Sent When Option Is Disabled - Enabled: false
    WakeUpMessage: "&aGood Morning!"

# AntiSpam Options
AntiSpam:
  Enabled: true

# AntiSwear Options
AntiSwear:
  # You Can Remove/Add Banned Words In plugins/UltraHardCore/Banned-Words.txt
  Enabled: true

# Forced ResourcePack Options
ForcedResourcePack:
  Enabled: false
  # ResourcePack .ZIP File URL - Our Official Hardcore Heart Pack:
  # https://uupload.ir/view/ultrahardcore_2a4.zip
  ResourcePackURL: "https://uupload.ir/view/ultrahardcore_2a4.zip"

# Death Title Options
Title:
  # Title Message When Player Died.
  TitleMessage: "&cYou Are Dead"
  # SubTitle Message When Player Died.
  SubTitleMessage: "&7You Can Edit This In Config.yml"
  # Fade In Time - Per Tick - 20 Tick = 1 Second
  FadeIn: 20
  # Stay Time - Per Tick - 20 Tick = 1 Second
  Stay: 50
  # Fade Out Time - Per Tick - 20 Tick = 1 Second
  FadeOut: 20