name: UltraHardCore
version: '${version}'
main: com.uhc.spigot.Main
api-version: 1.13
website: github.com/Mehran1022mm/UltraHardCore
commands:
  playtime:
    description: "see ur playtime."
  unban:
    description: "unban players."
  ultrahardcore:
    description: "plugin main command."
  ping:
    description: "return player ping."
  alert:
    description: "broadcast your message."
  socialmedia:
    description: "socialmedia command."
    aliases: [social, media, social-media]
  clearchat:
    description: "clears the chat."
  freeze:
    description: "freeze someone."
  unfreeze:
    description: "unfreeze someone."

